languageCode = "sk"
DefaultContentLanguage = "sk"
title = "SET NAME"
canonifyURLs = true
removePathAccents = true


[outputs]
home = [ "HTML"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
